
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.aug;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPEN_TAG = 2;
  public static final int error = 1;
  public static final int CLOSING_TAG = 4;
  public static final int CLOSED_TAG = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_TAG",
  "CLOSED_TAG",
  "CLOSING_TAG"
  };
}

